name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution

      - run: corepack enable
      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - name: auth aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::870424520169:role/gh-test-iam-odic
          aws-region: us-east-1

      - name: find aws env vars
        uses: actions/github-script@v7
        with:
          script: |
            Object.entries(process.env)
            .filter(([key, value]) => key.startsWith('AWS'))
            .forEach(([key, value]) => console.log(`${key}=${value}(${value.length})`))

      - name: test aws creds
        run: |
          aws sts get-caller-identity
      - run: pnpx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --with-env-vars="AWS_REGION,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY" --stop-agents-after="e2e-ci"
      - run: pnpm install --frozen-lockfile
      - run: pnpx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: yarn nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: pnpx nx affected -t lint test build e2e --parallel=1
